// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW6ls42sbaCIvkuSkvcsHmI7JKtmYhAlU',
    appId: '1:725995472063:web:d9b5b6885544a85815b20a',
    messagingSenderId: '725995472063',
    projectId: 'promoapp-a7a32',
    authDomain: 'promoapp-a7a32.firebaseapp.com',
    storageBucket: 'promoapp-a7a32.appspot.com',
    measurementId: 'G-EF9BCXL87S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6STghJX2hu37XIj6BP5vYVBNvM_8WW7Y',
    appId: '1:725995472063:android:fa2cbd0ce81d9d0815b20a',
    messagingSenderId: '725995472063',
    projectId: 'promoapp-a7a32',
    storageBucket: 'promoapp-a7a32.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUU2AeNLahdAHbPLXzJCe5O516rOS-4aY',
    appId: '1:725995472063:ios:7a85888aae2be14815b20a',
    messagingSenderId: '725995472063',
    projectId: 'promoapp-a7a32',
    storageBucket: 'promoapp-a7a32.appspot.com',
    iosClientId: '725995472063-5bdh1qtqi9dlgrcvog702b35nl3thq5c.apps.googleusercontent.com',
    iosBundleId: 'com.promo.promoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUU2AeNLahdAHbPLXzJCe5O516rOS-4aY',
    appId: '1:725995472063:ios:7a85888aae2be14815b20a',
    messagingSenderId: '725995472063',
    projectId: 'promoapp-a7a32',
    storageBucket: 'promoapp-a7a32.appspot.com',
    iosClientId: '725995472063-5bdh1qtqi9dlgrcvog702b35nl3thq5c.apps.googleusercontent.com',
    iosBundleId: 'com.promo.promoApp',
  );
}
